run migrations

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -220,6 +220,57 @@ jobs:
           workflowid:
             "${CIRCLE_WORKFLOW_ID:0:7}"      
 
+
+  run-migrations:
+    docker:
+      # Docker image here that supports NodeJS
+      - image: circleci/node:13.8.0
+    steps:
+      # Checkout code from git
+      - checkout
+      - restore_cache:
+          keys: [backend-build] 
+      - run:
+          name: Install dependencies
+          command: |
+            npm install curl 
+
+      - run:
+          name: Run migrations
+          command: |
+            # Your code here
+            cd backend
+            npm install
+            npm run migrations > migrations_dump.txt
+            #exit 1
+      - run:
+          name: Send migration results to memstash
+          command: |
+            # Your code here
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            then
+                # If you are using memstash.io, generate the token "7933fe63-4687-4fa1-8426-aa25aa1730ec" on the website
+                curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+                # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
+                curl https://kvdb.io/XEtP9sz3Uy2Lb7RWu996QY/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+                value=$(curl --insecure https://kvdb.io/XEtP9sz3Uy2Lb7RWu996QY/migration_${CIRCLE_WORKFLOW_ID:0:7})
+                echo $value
+            fi
+
+            #exit 1
+     # Here's where you will add some code to rollback on failure     
+     - destroy-environment:
+          workflowid:
+            "${CIRCLE_WORKFLOW_ID:0:7}"  
+
+
+
+
+
+
+
+
+
 workflows:
   default:
     jobs:
